/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const YiInput: typeof import('@yixianzi/components')['YiInput']
  const YiScrollData: typeof import('@yixianzi/components')['YiScrollData']
}
